name: Develop

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: 
      ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install robotframework
          pip install robotframework-requests
          pip install faker
          pip install robotframework-jsonlibrary
          pip install pyyaml

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results tests/fetuares/

      - name: Test Report
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://juliana-souza-franca.github.io/develop-api-robot-framework/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: robot-framework-report
          path: ./results/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./results/

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
